

upstream app {
    server 127.0.0.1:8004;
}

server {
    server_name signature-verification.net.ru www.signature-verification.net.ru;

    root /var/www/signature-verification.net.ru;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    access_log off;
    }

   
    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp|pdf|txt|xml)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
        try_files $uri =404;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/signature-verification.net.ru/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/signature-verification.net.ru/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 


}


server {
    if ($host = www.signature-verification.net.ru) {
        return 301 https://$host$request_uri;
    } 


    if ($host = signature-verification.net.ru) {
        return 301 https://$host$request_uri;
    }


    listen 80;
    server_name signature-verification.net.ru www.signature-verification.net.ru;
    return 404; # managed by Certbot




}
